version: "3"

services:
  nginx:
    ports:
      - 443:443
      - 80:80
    container_name: sonar-nginx
    image: nginx:1.19.1-alpine
    restart: unless-stopped
    depends_on:
      - sonarqube
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs/sonar:/etc/pki/tls/sonar
    networks:
      - sonar-network
  sonarqube:
    image: sonar:oc
    build: 
      context: .
      dockerfile: sonar.dockerfile
    depends_on:
      - db
    env_file: ./env/sonar.env
    restart: unless-stopped
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    expose:
      - "9000"
    networks:
      - sonar-network
  db:
    image: postgres:12
    restart: unless-stopped
    env_file: ./env/db.env
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - sonar-network

networks:
  sonar-network:
    driver: bridge
volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
  sonar_es_data:
